### ISSUE TITLE
Proxysql linux generic version failure to start on RHEL 8.6

### ISSUE THREAD

**Issue by chanakyakondam** [percona/proxysql-admin-tool-doc#94]
Hi,

We are trying to run Proxysql on RHEL 8.6 using generic packages from percona.(proxysql-2.4.8-Linux-x86_64.glibc2.27.tar).
We are getting following error when trying to start:
libgnutls.so.30.14.10: undefined symbol: nettle_secp_224r1, version HOGWEED_4

Thank you!

**Comment by patrickbirch** [comment]
Thank you, but this is not a valid pull request. 
You should consider [requesting a change with a Jira issue](https://github.com/percona/proxysql-admin-tool-doc/blob/main/contributing.md#request-a-change-with-a-jira-issue) or joining our Community forum and [adding a forum topic](https://github.com/percona/proxysql-admin-tool-doc/blob/main/contributing.md#add-a-forum-topic)
